# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMS-GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        Form.setStyleSheet("")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1031, 106))
        self.frame_2.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #080c15; \n"
"    border-right: 1px solid #151e2e;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton {\n"
"    color: #64748b; \n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    background-color: rgba(255, 255, 255, 0.02); \n"
"    height: 52px; \n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #0f172a;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 212, 255, 0.1), stop:1 rgba(0, 0, 0, 0));\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e293b;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 255, 204, 0.15);\n"
"    padding-top: 2px; \n"
"    padding-left: 17px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 rgba(0, 255, 204, 0.4), \n"
"        stop:0.4 rgba(0, 122, 255, 0.1), \n"
"        stop:1 rgba(0, 0, 0, 0));\n"
"    \n"
"    color: #00ffcc; \n"
"    font-size: 17px; \n"
"    border: 1px solid #005bb5; \n"
"    border-left: 6px solid #00ffcc; \n"
"    padding-left: 10px; \n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Gui-png/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setMaximumSize(QtCore.QSize(2, 16777215))
        self.frame_13.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_2.addWidget(self.frame_13)
        spacerItem = QtWidgets.QSpacerItem(343, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_43 = QtWidgets.QLabel(self.frame_2)
        self.label_43.setStyleSheet("QFrame {\n"
"    background-color: rgba(15, 23, 42, 0.6); /* Nền tối mờ */\n"
"    border: 1px solid #1e293b;\n"
"    border-top: none; /* Xóa viền trên để dính chặt vào nóc */\n"
"    border-bottom-left-radius: 15px; /* Bo tròn góc xệ xuống */\n"
"    border-bottom-right-radius: 15px;\n"
"}\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_2.addWidget(self.label_43)
        spacerItem1 = QtWidgets.QSpacerItem(343, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_19.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Gui-png/bluetooth1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_19.setIcon(icon1)
        self.pushButton_19.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_2.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_20.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Gui-png/lte1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon2)
        self.pushButton_20.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_2.addWidget(self.pushButton_20)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 530, 1031, 104))
        self.frame_3.setStyleSheet("/* Khung nền chính (Sidebar) */\n"
"QFrame {\n"
"    background-color: #080c15; \n"
"    border-right: 1px solid #151e2e;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* THÊM MỚI: Định dạng cho mọi chữ (Label) thả vào khung này sẽ auto màu Trắng */\n"
"QLabel {\n"
"    color: #ffffff; \n"
"    background-color: transparent; /* Tẩy nền xám */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Các nút bấm (Giữ nguyên của chàng vì đã quá đẹp) */\n"
"QPushButton {\n"
"    color: #64748b; \n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    background-color: rgba(255, 255, 255, 0.02); \n"
"    height: 52px; \n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #0f172a;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 212, 255, 0.1), stop:1 rgba(0, 0, 0, 0));\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e293b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 255, 204, 0.15);\n"
"    padding-top: 2px; \n"
"    padding-left: 17px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 rgba(0, 255, 204, 0.4), \n"
"        stop:0.4 rgba(0, 122, 255, 0.1), \n"
"        stop:1 rgba(0, 0, 0, 0));\n"
"    color: #00ffcc; \n"
"    font-size: 17px; \n"
"    border: 1px solid #005bb5; \n"
"    border-left: 6px solid #00ffcc; \n"
"    padding-left: 10px; \n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Gui-png/directions_car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Gui-png/widgets_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Gui-png/arrow_back_ios_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Gui-png/arrow_forward_ios_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon6)
        self.pushButton_12.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_13.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Gui-png/toys_fan_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon7)
        self.pushButton_13.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon5)
        self.pushButton_14.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon6)
        self.pushButton_15.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout.addWidget(self.pushButton_15)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_17.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Gui-png/cool_to_dry_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon8)
        self.pushButton_17.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout.addWidget(self.pushButton_17)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_16.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Gui-png/windshield_defrost_rear_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon9)
        self.pushButton_16.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout.addWidget(self.pushButton_16)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border-radius: 6px;\n"
"}")
        self.pushButton_18.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Gui-png/volume_up_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon10)
        self.pushButton_18.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout.addWidget(self.pushButton_18)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(160, 60, 531, 301))
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: #111827; /* Màu xanh đen sâu */\n"
"    border: 1px solid #1f2937; /* Viền mờ tinh tế */\n"
"    border-radius: 12px; /* Bo góc đồng bộ */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(140, 120, 341, 191))
        self.label.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/Gui-png/ev_bms_reference_match.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_38 = QtWidgets.QLabel(self.frame_4)
        self.label_38.setGeometry(QtCore.QRect(40, 30, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.txt_soc_total = QtWidgets.QLabel(self.frame_4)
        self.txt_soc_total.setGeometry(QtCore.QRect(40, 60, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.txt_soc_total.setFont(font)
        self.txt_soc_total.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá dạ quang rực rỡ */\n"
"    background-color: transparent; /* Tẩy viền/nền xám */\n"
"    font-weight: bold;\n"
"    font-size: 24px; /* Phóng to số lên nếu cần */\n"
"}")
        self.txt_soc_total.setObjectName("txt_soc_total")
        self.progressBar_7 = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar_7.setGeometry(QtCore.QRect(30, 90, 118, 6))
        self.progressBar_7.setStyleSheet("QProgressBar {\n"
"    background-color: #1a2436; \n"
"    border: none;\n"
"    border-radius: 2px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    /* Chuyển màu từ Xanh dương đậm sang Xanh dương lơ (Cyan) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #2563eb, stop:1 #06b6d4);\n"
"    border-radius: 2px;\n"
"}")
        self.progressBar_7.setProperty("value", 80)
        self.progressBar_7.setTextVisible(False)
        self.progressBar_7.setObjectName("progressBar_7")
        self.label_40 = QtWidgets.QLabel(self.frame_4)
        self.label_40.setGeometry(QtCore.QRect(30, 120, 181, 17))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_4)
        self.label_41.setGeometry(QtCore.QRect(30, 150, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("QLabel {\n"
"    color: #0ea5e9; /* Màu xanh dương sáng */\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    background-color: transparent;\n"
"}")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_4)
        self.label_42.setGeometry(QtCore.QRect(70, 150, 67, 17))
        self.label_42.setObjectName("label_42")
        self.label_23 = QtWidgets.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(390, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.txt_current = QtWidgets.QLabel(self.frame_4)
        self.txt_current.setGeometry(QtCore.QRect(400, 60, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.txt_current.setFont(font)
        self.txt_current.setStyleSheet("QLabel {\n"
"    color: #0ea5e9; /* Màu xanh dương sáng */\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    background-color: transparent;\n"
"}")
        self.txt_current.setObjectName("txt_current")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(170, 360, 131, 171))
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color: #111827; /* Màu xanh đen sâu */\n"
"    border: 1px solid #1f2937; /* Viền mờ tinh tế */\n"
"    border-radius: 12px; /* Bo góc đồng bộ */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 67, 17))
        self.label_2.setObjectName("label_2")
        self.txt_volt_cell1 = QtWidgets.QLabel(self.frame_5)
        self.txt_volt_cell1.setGeometry(QtCore.QRect(30, 50, 71, 31))
        self.txt_volt_cell1.setStyleSheet("QLabel {\n"
"    font-size: 24px; /* Phóng to hẳn lên */\n"
"    background-color: transparent;\n"
"}")
        self.txt_volt_cell1.setObjectName("txt_volt_cell1")
        self.bar_soc_cell1 = QtWidgets.QProgressBar(self.frame_5)
        self.bar_soc_cell1.setGeometry(QtCore.QRect(10, 90, 101, 23))
        self.bar_soc_cell1.setStyleSheet("/* Thiết lập cái rãnh (nền) của thanh pin */\n"
"QProgressBar {\n"
"    background-color: #131c2b; /* Màu xanh đen rất sâu, tệp với nền */\n"
"    border: none; /* Xóa viền hoàn toàn */\n"
"    border-radius: 4px; /* Bo góc nhẹ */\n"
"    text-align: center;\n"
"    color: transparent; /* Giấu số % đi */\n"
"}\n"
"\n"
"/* Thiết lập phần lõi pin (Chunk) đang chạy */\n"
"QProgressBar::chunk {\n"
"    /* Chuyển màu từ Cyan (xanh ngọc) sang Lime (xanh lá sáng) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 #0dcaf0, \n"
"        stop:1 #8cc63f);\n"
"    border-radius: 4px;\n"
"}")
        self.bar_soc_cell1.setProperty("value", 80)
        self.bar_soc_cell1.setObjectName("bar_soc_cell1")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 51, 17))
        self.label_4.setObjectName("label_4")
        self.txt_soh_cell1 = QtWidgets.QLabel(self.frame_5)
        self.txt_soh_cell1.setGeometry(QtCore.QRect(60, 130, 67, 17))
        self.txt_soh_cell1.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá rực rỡ */\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"}")
        self.txt_soh_cell1.setObjectName("txt_soh_cell1")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(90, 20, 31, 17))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Gui-png/verified_user_24dp_75FB4C_FILL0_wght400_GRAD0_opsz24.png"))
        self.label_6.setObjectName("label_6")
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(690, 60, 341, 471))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: rgba(20, 26, 38, 0.7); /* Màu xanh đen trong suốt */\n"
"    border: 1px solid #1f2a3a; /* Viền xanh sáng mờ */\n"
"    border-radius: 12px; /* Bo góc mềm mại */\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setGeometry(QtCore.QRect(0, 320, 341, 151))
        self.frame_10.setStyleSheet("QFrame {\n"
"    background-color: rgba(20, 26, 38, 0.7); /* Màu xanh đen trong suốt */\n"
"    border: 1px solid #1f2a3a; /* Viền xanh sáng mờ */\n"
"    border-radius: 12px; /* Bo góc mềm mại */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_22 = QtWidgets.QLabel(self.frame_10)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.txt_total_volt = QtWidgets.QLabel(self.frame_10)
        self.txt_total_volt.setGeometry(QtCore.QRect(270, 10, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_total_volt.setFont(font)
        self.txt_total_volt.setObjectName("txt_total_volt")
        self.chart_voltage = QtWidgets.QWidget(self.frame_10)
        self.chart_voltage.setGeometry(QtCore.QRect(10, 40, 311, 101))
        self.chart_voltage.setObjectName("chart_voltage")
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 350, 191))
        self.frame_11.setStyleSheet("QFrame {\n"
"    background-color: rgba(20, 26, 38, 0.7); /* Màu xanh đen trong suốt */\n"
"    border: 1px solid #1f2a3a; /* Viền xanh sáng mờ */\n"
"    border-radius: 12px; /* Bo góc mềm mại */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_24 = QtWidgets.QLabel(self.frame_11)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_11)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_11)
        self.label_26.setGeometry(QtCore.QRect(230, 40, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.bar_soh_total = QtWidgets.QProgressBar(self.frame_11)
        self.bar_soh_total.setGeometry(QtCore.QRect(10, 100, 291, 23))
        self.bar_soh_total.setStyleSheet("/* Rãnh pin (Phần nền chưa sạc) */\n"
"QProgressBar {\n"
"    background-color: #1a2436; /* Xanh đen tối màu, chìm vào nền */\n"
"    border: none;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/* Lõi pin (Phần dung lượng phát sáng) */\n"
"QProgressBar::chunk {\n"
"    /* Dải gradient chuyển từ màu xanh lá đậm sang xanh lá dạ quang (Neon) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 #22c55e, \n"
"        stop:1 #4ade80);\n"
"    border-radius: 2px;\n"
"}")
        self.bar_soh_total.setProperty("value", 80)
        self.bar_soh_total.setObjectName("bar_soh_total")
        self.txt_soh_total = QtWidgets.QLabel(self.frame_11)
        self.txt_soh_total.setGeometry(QtCore.QRect(10, 66, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.txt_soh_total.setFont(font)
        self.txt_soh_total.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá dạ quang rực rỡ */\n"
"    background-color: transparent; /* Tẩy viền/nền xám */\n"
"    font-weight: bold;\n"
"    font-size: 24px; /* Phóng to số lên nếu cần */\n"
"}")
        self.txt_soh_total.setWordWrap(False)
        self.txt_soh_total.setObjectName("txt_soh_total")
        self.txt_degradation = QtWidgets.QLabel(self.frame_11)
        self.txt_degradation.setGeometry(QtCore.QRect(230, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.txt_degradation.setFont(font)
        self.txt_degradation.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá dạ quang rực rỡ */\n"
"    background-color: transparent; /* Tẩy viền/nền xám */\n"
"    font-weight: bold;\n"
"    font-size: 24px; /* Phóng to số lên nếu cần */\n"
"}")
        self.txt_degradation.setObjectName("txt_degradation")
        self.label_29 = QtWidgets.QLabel(self.frame_11)
        self.label_29.setGeometry(QtCore.QRect(10, 130, 81, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_11)
        self.label_30.setGeometry(QtCore.QRect(230, 130, 81, 17))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_11)
        self.label_31.setGeometry(QtCore.QRect(20, 156, 61, 31))
        self.label_31.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá dạ quang rực rỡ */\n"
"    background-color: transparent; /* Tẩy viền/nền xám */\n"
"    font-weight: bold;\n"
"    font-size: 24px; /* Phóng to số lên nếu cần */\n"
"}")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_11)
        self.label_32.setGeometry(QtCore.QRect(230, 160, 91, 17))
        self.label_32.setObjectName("label_32")
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setGeometry(QtCore.QRect(0, 190, 341, 131))
        self.frame_12.setStyleSheet("QFrame {\n"
"    background-color: rgba(20, 26, 38, 0.7); /* Màu xanh đen trong suốt */\n"
"    border: 1px solid #1f2a3a; /* Viền xanh sáng mờ */\n"
"    border-radius: 12px; /* Bo góc mềm mại */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.bar_temperature = QtWidgets.QProgressBar(self.frame_12)
        self.bar_temperature.setGeometry(QtCore.QRect(60, 60, 231, 23))
        self.bar_temperature.setStyleSheet("/* Thiết lập cái rãnh (nền) của thanh pin */\n"
"QProgressBar {\n"
"    background-color: #131c2b; /* Màu xanh đen rất sâu, tệp với nền */\n"
"    border: none; /* Xóa viền hoàn toàn */\n"
"    border-radius: 4px; /* Bo góc nhẹ */\n"
"    text-align: center;\n"
"    color: transparent; /* Giấu số % đi */\n"
"}\n"
"\n"
"/* Thiết lập phần lõi pin (Chunk) đang chạy */\n"
"QProgressBar::chunk {\n"
"    /* Chuyển màu từ Cyan (xanh ngọc) sang Lime (xanh lá sáng) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 #0dcaf0, \n"
"        stop:1 #8cc63f);\n"
"    border-radius: 4px;\n"
"}")
        self.bar_temperature.setProperty("value", 80)
        self.bar_temperature.setObjectName("bar_temperature")
        self.label_33 = QtWidgets.QLabel(self.frame_12)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_12)
        self.label_34.setGeometry(QtCore.QRect(60, 100, 21, 17))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_12)
        self.label_35.setGeometry(QtCore.QRect(160, 100, 21, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_12)
        self.label_36.setGeometry(QtCore.QRect(270, 100, 51, 21))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_12)
        self.label_37.setGeometry(QtCore.QRect(30, 60, 21, 21))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("Gui-png/thermometer_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))
        self.label_37.setObjectName("label_37")
        self.txt_temperature = QtWidgets.QLabel(self.frame_12)
        self.txt_temperature.setGeometry(QtCore.QRect(220, 20, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_temperature.setFont(font)
        self.txt_temperature.setObjectName("txt_temperature")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 60, 171, 471))
        self.frame.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #080c15; \n"
"    border-right: 1px solid #151e2e;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton {\n"
"    color: #64748b; \n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    background-color: rgba(255, 255, 255, 0.02); \n"
"    height: 52px; \n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #0f172a;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 212, 255, 0.1), stop:1 rgba(0, 0, 0, 0));\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e293b;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 255, 204, 0.15);\n"
"    padding-top: 2px; \n"
"    padding-left: 17px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 rgba(0, 255, 204, 0.4), \n"
"        stop:0.4 rgba(0, 122, 255, 0.1), \n"
"        stop:1 rgba(0, 0, 0, 0));\n"
"    \n"
"    color: #00ffcc; \n"
"    font-size: 17px; \n"
"    border: 1px solid #005bb5; \n"
"    border-left: 6px solid #00ffcc; \n"
"    padding-left: 10px; \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setEnabled(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/Gui-png/battery_6_bar_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon11)
        self.pushButton.setIconSize(QtCore.QSize(20, 30))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/Gui-png/battery_charging_full_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon12)
        self.pushButton_2.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/Gui-png/grid_4x4_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon13)
        self.pushButton_3.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/Gui-png/warning_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon14)
        self.pushButton_4.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/Gui-png/history_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon15)
        self.pushButton_5.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setAutoExclusive(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/Gui-png/settings_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon16)
        self.pushButton_6.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(300, 360, 131, 171))
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color: #111827; /* Màu xanh đen sâu */\n"
"    border: 1px solid #1f2937; /* Viền mờ tinh tế */\n"
"    border-radius: 12px; /* Bo góc đồng bộ */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 67, 17))
        self.label_7.setObjectName("label_7")
        self.txt_volt_cell2 = QtWidgets.QLabel(self.frame_7)
        self.txt_volt_cell2.setGeometry(QtCore.QRect(30, 50, 71, 31))
        self.txt_volt_cell2.setStyleSheet("QLabel {\n"
"    font-size: 24px; /* Phóng to hẳn lên */\n"
"    background-color: transparent;\n"
"}")
        self.txt_volt_cell2.setObjectName("txt_volt_cell2")
        self.bar_soc_cell2 = QtWidgets.QProgressBar(self.frame_7)
        self.bar_soc_cell2.setGeometry(QtCore.QRect(10, 90, 101, 23))
        self.bar_soc_cell2.setStyleSheet("/* Thiết lập cái rãnh (nền) của thanh pin */\n"
"QProgressBar {\n"
"    background-color: #131c2b; /* Màu xanh đen rất sâu, tệp với nền */\n"
"    border: none; /* Xóa viền hoàn toàn */\n"
"    border-radius: 4px; /* Bo góc nhẹ */\n"
"    text-align: center;\n"
"    color: transparent; /* Giấu số % đi */\n"
"}\n"
"\n"
"/* Thiết lập phần lõi pin (Chunk) đang chạy */\n"
"QProgressBar::chunk {\n"
"    /* Chuyển màu từ Cyan (xanh ngọc) sang Lime (xanh lá sáng) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 #0dcaf0, \n"
"        stop:1 #8cc63f);\n"
"    border-radius: 4px;\n"
"}")
        self.bar_soc_cell2.setProperty("value", 80)
        self.bar_soc_cell2.setObjectName("bar_soc_cell2")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 51, 17))
        self.label_9.setObjectName("label_9")
        self.txt_soh_cell2 = QtWidgets.QLabel(self.frame_7)
        self.txt_soh_cell2.setGeometry(QtCore.QRect(60, 130, 67, 17))
        self.txt_soh_cell2.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá rực rỡ */\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"}")
        self.txt_soh_cell2.setObjectName("txt_soh_cell2")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(90, 20, 31, 17))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Gui-png/verified_user_24dp_75FB4C_FILL0_wght400_GRAD0_opsz24.png"))
        self.label_11.setObjectName("label_11")
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setGeometry(QtCore.QRect(430, 360, 131, 171))
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color: #111827; /* Màu xanh đen sâu */\n"
"    border: 1px solid #1f2937; /* Viền mờ tinh tế */\n"
"    border-radius: 12px; /* Bo góc đồng bộ */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 67, 17))
        self.label_12.setObjectName("label_12")
        self.txt_volt_cell3 = QtWidgets.QLabel(self.frame_8)
        self.txt_volt_cell3.setGeometry(QtCore.QRect(40, 50, 71, 31))
        self.txt_volt_cell3.setStyleSheet("QLabel {\n"
"    font-size: 24px; /* Phóng to hẳn lên */\n"
"    background-color: transparent;\n"
"}")
        self.txt_volt_cell3.setObjectName("txt_volt_cell3")
        self.bar_soc_cell3 = QtWidgets.QProgressBar(self.frame_8)
        self.bar_soc_cell3.setGeometry(QtCore.QRect(10, 90, 101, 23))
        self.bar_soc_cell3.setStyleSheet("/* Thiết lập cái rãnh (nền) của thanh pin */\n"
"QProgressBar {\n"
"    background-color: #131c2b; /* Màu xanh đen rất sâu, tệp với nền */\n"
"    border: none; /* Xóa viền hoàn toàn */\n"
"    border-radius: 4px; /* Bo góc nhẹ */\n"
"    text-align: center;\n"
"    color: transparent; /* Giấu số % đi */\n"
"}\n"
"\n"
"/* Thiết lập phần lõi pin (Chunk) đang chạy */\n"
"QProgressBar::chunk {\n"
"    /* Chuyển màu từ Cyan (xanh ngọc) sang Lime (xanh lá sáng) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 #0dcaf0, \n"
"        stop:1 #8cc63f);\n"
"    border-radius: 4px;\n"
"}")
        self.bar_soc_cell3.setProperty("value", 80)
        self.bar_soc_cell3.setObjectName("bar_soc_cell3")
        self.label_14 = QtWidgets.QLabel(self.frame_8)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 51, 17))
        self.label_14.setObjectName("label_14")
        self.txt_soh_cell3 = QtWidgets.QLabel(self.frame_8)
        self.txt_soh_cell3.setGeometry(QtCore.QRect(60, 130, 67, 17))
        self.txt_soh_cell3.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá rực rỡ */\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"}")
        self.txt_soh_cell3.setObjectName("txt_soh_cell3")
        self.label_16 = QtWidgets.QLabel(self.frame_8)
        self.label_16.setGeometry(QtCore.QRect(90, 20, 31, 17))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Gui-png/verified_user_24dp_75FB4C_FILL0_wght400_GRAD0_opsz24.png"))
        self.label_16.setObjectName("label_16")
        self.frame_9 = QtWidgets.QFrame(Form)
        self.frame_9.setGeometry(QtCore.QRect(560, 360, 131, 171))
        self.frame_9.setStyleSheet("QFrame {\n"
"    background-color: #111827; /* Màu xanh đen sâu */\n"
"    border: 1px solid #1f2937; /* Viền mờ tinh tế */\n"
"    border-radius: 12px; /* Bo góc đồng bộ */\n"
"}\n"
"/* Phép thuật biến hóa toàn bộ chữ trong khung */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ffffff; /* Đặt màu trắng làm mặc định cho các chữ */\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 67, 17))
        self.label_17.setObjectName("label_17")
        self.txt_volt_cell4 = QtWidgets.QLabel(self.frame_9)
        self.txt_volt_cell4.setGeometry(QtCore.QRect(30, 50, 71, 31))
        self.txt_volt_cell4.setStyleSheet("QLabel {\n"
"    font-size: 24px; /* Phóng to hẳn lên */\n"
"    background-color: transparent;\n"
"}")
        self.txt_volt_cell4.setObjectName("txt_volt_cell4")
        self.bar_soc_cell4 = QtWidgets.QProgressBar(self.frame_9)
        self.bar_soc_cell4.setGeometry(QtCore.QRect(10, 90, 101, 23))
        self.bar_soc_cell4.setStyleSheet("/* Thiết lập cái rãnh (nền) của thanh pin */\n"
"QProgressBar {\n"
"    background-color: #131c2b; /* Màu xanh đen rất sâu, tệp với nền */\n"
"    border: none; /* Xóa viền hoàn toàn */\n"
"    border-radius: 4px; /* Bo góc nhẹ */\n"
"    text-align: center;\n"
"    color: transparent; /* Giấu số % đi */\n"
"}\n"
"\n"
"/* Thiết lập phần lõi pin (Chunk) đang chạy */\n"
"QProgressBar::chunk {\n"
"    /* Chuyển màu từ Cyan (xanh ngọc) sang Lime (xanh lá sáng) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 #0dcaf0, \n"
"        stop:1 #8cc63f);\n"
"    border-radius: 4px;\n"
"}")
        self.bar_soc_cell4.setProperty("value", 80)
        self.bar_soc_cell4.setObjectName("bar_soc_cell4")
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setGeometry(QtCore.QRect(10, 127, 51, 20))
        self.label_19.setObjectName("label_19")
        self.txt_soh_cell4 = QtWidgets.QLabel(self.frame_9)
        self.txt_soh_cell4.setGeometry(QtCore.QRect(60, 130, 67, 17))
        self.txt_soh_cell4.setStyleSheet("QLabel {\n"
"    color: #4ade80; /* Màu xanh lá rực rỡ */\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"}")
        self.txt_soh_cell4.setObjectName("txt_soh_cell4")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setGeometry(QtCore.QRect(90, 20, 31, 17))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("Gui-png/verified_user_24dp_75FB4C_FILL0_wght400_GRAD0_opsz24.png"))
        self.label_21.setObjectName("label_21")
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.frame_6.raise_()
        self.frame.raise_()
        self.frame_7.raise_()
        self.frame_5.raise_()
        self.frame_3.raise_()
        self.frame_9.raise_()
        self.frame_8.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_43.setText(_translate("Form", "10:30"))
        self.label_38.setText(_translate("Form", "SOC"))
        self.txt_soc_total.setText(_translate("Form", "73%"))
        self.label_40.setText(_translate("Form", "Quãng đường ước tính"))
        self.label_41.setText(_translate("Form", "312"))
        self.label_42.setText(_translate("Form", "Km"))
        self.label_23.setText(_translate("Form", "Dòng điện"))
        self.txt_current.setText(_translate("Form", "36A"))
        self.label_2.setText(_translate("Form", "Cell 1"))
        self.txt_volt_cell1.setText(_translate("Form", "3.2V"))
        self.label_4.setText(_translate("Form", "SOH"))
        self.txt_soh_cell1.setText(_translate("Form", "96%"))
        self.label_22.setText(_translate("Form", "Điện áp"))
        self.txt_total_volt.setText(_translate("Form", "36A"))
        self.label_24.setText(_translate("Form", "Tình trạng pin"))
        self.label_25.setText(_translate("Form", "SOH"))
        self.label_26.setText(_translate("Form", "Độ chai"))
        self.txt_soh_total.setText(_translate("Form", "93%"))
        self.txt_degradation.setText(_translate("Form", "6.8%"))
        self.label_29.setText(_translate("Form", "Tình trạng"))
        self.label_30.setText(_translate("Form", "Chu kì sạc"))
        self.label_31.setText(_translate("Form", "Tốt"))
        self.label_32.setText(_translate("Form", "136 chu kỳ"))
        self.label_33.setText(_translate("Form", "Nhiệt độ"))
        self.label_34.setText(_translate("Form", "L"))
        self.label_35.setText(_translate("Form", "M"))
        self.label_36.setText(_translate("Form", "H"))
        self.txt_temperature.setText(_translate("Form", "31℃"))
        self.pushButton.setText(_translate("Form", "Tổng quan"))
        self.pushButton_2.setText(_translate("Form", "Pin"))
        self.pushButton_3.setText(_translate("Form", "Cell"))
        self.pushButton_4.setText(_translate("Form", "Cảnh báo"))
        self.pushButton_5.setText(_translate("Form", "Lịch sử"))
        self.pushButton_6.setText(_translate("Form", "Cài đặt"))
        self.label_7.setText(_translate("Form", "Cell 2"))
        self.txt_volt_cell2.setText(_translate("Form", "3.2V"))
        self.label_9.setText(_translate("Form", "SOH"))
        self.txt_soh_cell2.setText(_translate("Form", "96%"))
        self.label_12.setText(_translate("Form", "Cell 3"))
        self.txt_volt_cell3.setText(_translate("Form", "3.2V"))
        self.label_14.setText(_translate("Form", "SOH"))
        self.txt_soh_cell3.setText(_translate("Form", "96%"))
        self.label_17.setText(_translate("Form", "Cell 3"))
        self.txt_volt_cell4.setText(_translate("Form", "3.2V"))
        self.label_19.setText(_translate("Form", "SOH"))
        self.txt_soh_cell4.setText(_translate("Form", "96%"))
import bms_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
